version: 0.2
phases:
  pre-build:
    commands:
    - echo "Entering PRE-BUILD phase"
  build:
    commands:
    - echo "Entering BUILD phase"
    - mvn clean prepare-package war:explode
  post-build:
    commands:
      - echo "Entering POST-BUILD phase"
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*